[general]
live_config_reload = true

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 5

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Shift"

[window]
decorations = "None"
dynamic_title = true
startup_mode = "Fullscreen"
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 150
lines = 35

[window.padding]
x = 15
y = 15
